---
- name: 创建临时目录
  file: dest={{ tmp_dir }} state=directory

- name: 拷贝nginx,keepalived安装包
  unarchive: src={{ software_dir }}/ha.tar.gz dest={{ tmp_dir }}

- name: 安装keepalived高可用软件
  yum: name={{ tmp_dir }}/{{ item }} state=present
  with_items:
    - "net-snmp-libs-5.7.2-43.el7.x86_64.rpm"
    - "net-snmp-agent-libs-5.7.2-43.el7.x86_64.rpm"
    - "keepalived-1.3.5-16.el7.x86_64.rpm"

#- name: 安装nginx负载均衡器
#  yum: name={{ tmp_dir }}/nginx-1.16.1-1.el7.ngx.x86_64.rpm state=present

- name: 安装haproxy负载均衡器
  yum: name={{ tmp_dir }}/haproxy-1.5.18-9.el7_9.1.x86_64.rpm state=present

#- name: 拷贝nginx配置文件
#  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: 拷贝haproxy配置文件
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: 拷贝keepalived配置文件       
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: 拷贝nginx健康检查脚本
  #copy: src=check_nginx.sh dest=/etc/keepalived/ mode=u+x
  copy: src=check_apiserver.sh dest=/etc/keepalived/ mode=u+x

- name: 启动服务
  systemd: name={{ item }} state=restarted enabled=yes daemon_reload=yes
  with_items:
    #- nginx
    - haproxy 
    - keepalived
